-- Tables this pipeline writes to.
-- The pipeline also tries to create them at runtime (SQLModel, checkfirst=True),
-- but that needs DDL rights on the schema; run this once as a DBA if the app
-- role can't create tables.

-- Registry of the tracked editorial playlists. Mirrors EDITORIALS in
-- src/consts.py; the pipeline upserts it on every run.
CREATE TABLE IF NOT EXISTS social_golden_data.editorial_playlists (
    playlist_id   text PRIMARY KEY,
    playlist_name text NOT NULL
);

-- One row per stint of a track in a playlist, one row per credited artist.
-- start_date : first run that saw the track in the playlist (this stint).
-- end_date   : NULL while the track is still in the playlist; set to the last
--              date it was present once a run finds it gone.
-- Which stints are open is tracked in the state file (src/state.py), not here.
-- A track that leaves and later returns gets a new row.
CREATE TABLE IF NOT EXISTS social_golden_data.editorial_playlists_storico (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playlist_id   text NOT NULL
                  REFERENCES social_golden_data.editorial_playlists (playlist_id),
    playlist_name text,
    track_name    text,
    track_id      text NOT NULL,          -- Spotify track id, from the embed
    artist_name   text,                   -- one credited artist (embed subtitle, split)
    artist_id     text,                   -- resolved from our data or Apify; NULL if unknown
    start_date    date NOT NULL,
    end_date      date                    -- NULL = stint still open
);

-- Open stints, looked up on every run's reconstruct path.
CREATE INDEX IF NOT EXISTS ix_eps_open
    ON social_golden_data.editorial_playlists_storico (playlist_id, track_id)
    WHERE end_date IS NULL;
CREATE INDEX IF NOT EXISTS ix_eps_playlist_track
    ON social_golden_data.editorial_playlists_storico (playlist_id, track_id);
CREATE INDEX IF NOT EXISTS ix_eps_track_id
    ON social_golden_data.editorial_playlists_storico (track_id);
CREATE INDEX IF NOT EXISTS ix_eps_artist_id
    ON social_golden_data.editorial_playlists_storico (artist_id);
