-- Tables this pipeline writes to.
-- The pipeline also tries to create them at runtime (SQLModel, checkfirst=True),
-- but that needs DDL rights on the schema; run this once as a DBA if the app
-- role can't create tables.

-- Registry of the tracked editorial playlists. Mirrors EDITORIALS in
-- src/consts.py; the pipeline upserts it on every run.
CREATE TABLE IF NOT EXISTS social_golden_data.editorial_playlists (
    playlist_id   text PRIMARY KEY,
    playlist_name text NOT NULL
);

-- One row per stint of a track in a playlist, one row per credited artist name.
-- start_date : first run that saw the track in the playlist (this stint).
-- end_date   : NULL while the track is still in the playlist; set to the run
--              date that first found it gone.
-- This table is the state: a stint is open while end_date IS NULL. A track that
-- leaves and later returns gets a new row.
CREATE TABLE IF NOT EXISTS social_golden_data.editorial_playlists_storico (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playlist_id   text NOT NULL
                  REFERENCES social_golden_data.editorial_playlists (playlist_id),
    playlist_name text,
    track_name    text,
    track_id      text NOT NULL,          -- Spotify track id, from the embed
    artist_name   text,                   -- one credited artist (embed subtitle, split)
    start_date    date NOT NULL,
    end_date      date                    -- NULL = stint still open
);

-- At most one open stint per (playlist, track, artist name); also the index the
-- run uses to read the current open state. COALESCE so two NULL-artist rows for
-- the same track still collide.
CREATE UNIQUE INDEX IF NOT EXISTS ux_eps_open
    ON social_golden_data.editorial_playlists_storico
       (playlist_id, track_id, COALESCE(artist_name, ''))
    WHERE end_date IS NULL;
CREATE INDEX IF NOT EXISTS ix_eps_playlist_track
    ON social_golden_data.editorial_playlists_storico (playlist_id, track_id);
CREATE INDEX IF NOT EXISTS ix_eps_track_id
    ON social_golden_data.editorial_playlists_storico (track_id);
